[package]
name = "pngme"
description = "Utility for encoding and decoding messages in PNG files"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
crc = "3.2.1"
